trigger:
- main

pool:
  name: 'CartFlow-Agent-Pool'

steps:

- checkout: self
  displayName: 'Checkout CartFlow Source Code'

- script: |
    echo "Checking build environment..."
    java -version
    mvn -version
    git --version
  displayName: 'Verify Build Tools'

# Prepare SonarQube analysis
- task: SonarQubePrepare@8
  displayName: 'Prepare SonarQube Analysis'
  inputs:
    SonarQube: 'CartFlow-SonarQube'
    scannerMode: 'other'
    extraProperties: |
      sonar.projectKey=CartFlow
      sonar.projectName=CartFlow
      sonar.branch.name=

# Maven build, tests, package, and SonarQube analysis
- task: Maven@4
  displayName: 'Maven Build, Test and SonarQube Analysis'
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'Path'
    jdkDirectory: '/usr/lib/jvm/java-17-openjdk-amd64'
    mavenVersionOption: 'Default'
    sonarQubeRunAnalysis: true

# Publish SonarQube Quality Gate
- task: SonarQubePublish@8
  displayName: 'Publish SonarQube Quality Gate'
  inputs:
    pollingTimeoutSec: '300'

# Publish CartFlow JAR
- task: PublishPipelineArtifact@1
  displayName: 'Publish CartFlow JAR'
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)/target'
    artifact: 'CartFlow'